### ISSUE TITLE
Data production

### ISSUE THREAD

**Issue by l1uw3n** [redouanelg/EddyNet#1]
How is this data produced?

**Comment by redouanelg** [comment]
@l1uw3n Hi, sorry for the late answer, everything is explained in my IGARSS paper, we constructed the training dataset using results from py-eddy-tracker. It yields centers and boundaries of eddies, then we used a simple script to transform them to segmentation maps using Polygons (from Shapely library)

**Comment by shmr123** [comment]
Can you share the script?
